### ISSUE TITLE
オフライン時 or サーバーダウン時の処理

### ISSUE THREAD

**Issue by yukikurage** [traPtitech/trap-collection-launcher#59]
axiosがエラーを吐いたときに，モーダルを出してオフライン状態orサーバーダウン時である旨を表示したいです．
タイトルは「サーバーへの接続に失敗しました」，本文は「サーバーへの接続に失敗しました．アプリを閉じますか？」，キャンセルは「再試行」，OKは「閉じる」
を考えているのですがどうですか

**Comment by JichouP** [comment]
@yukikurage 
遅くなりました:pray:
良いと思います！これで進めてください！
