### ISSUE TITLE
ゲームアップデート時に既存のセーブデータが消える

### ISSUE THREAD

**Issue by yukikurage** [traPtitech/trap-collection-launcher#89]
おそらくサーバー側の改修が必要です．
例えば `main.exe` と`save.json`が１つのフォルダに入っているゲーム構成だとすると，ゲームがアプデされたとき`main.exe`は置き換えて`save.json`は置き換えないと言った操作が必要になりますが，ランチャー側からだとどちらがセーブファイルかの見分けはつかないので不可能です．
したがってサーバー側に手を入れて，`entryPoint`と同じように`saveData`などのプロパティも帰ってくるようにするぐらいしか思いつきません．
どうでしょうか

**Comment by anko9801** [comment]
大体上手くいきそうだけど複雑になってくると厳しそう。
ある部分だけをアップデートさせるのはどうなんだろう。例えばexeとかの実行ファイルだけ入れ替えるとか。入れ替えるべきファイルは調べないと分からないけど一般的に対応できそう。

**Comment by yukikurage** [comment]
拡張子で判別するのも考えたけど，例えばノベルゲーで文章データとセーブデータどっちもjsonだったら死ぬし，更新すべきデータもexeだけでなくpngとかjpgもあるかも知れないのできつそう

**Comment by anko9801** [comment]
クソ雑だけど書き込みが加えられたファイルは更新しないとしたらどうだろう。セーブデータ以外にファイルを更新したくなることある？

**Comment by yukikurage** [comment]
うーん、ちなみに
> 複雑になってくると確認するのが大変だし厳しそう。
これはなにを確認するという意味？

**Comment by anko9801** [comment]
セーブデータが複数のファイルに跨っている場合に、見逃したらバグになるので確認するべきなんだけど、それが手間で製作者呼ばないとわからないものもありそうだなと思った。
でも今言ったhash取る方法で対応できそう。

**Comment by JichouP** [comment]
ひとまず保留で

traPの共通認識としてのゲームの販売やアップデートの方針を決める必要があると思うので、一回役員会に問い合わせしましょう
